## Récupérer les entreprises
GET http://localhost:3000/api/admin/company
Content-Type: application/json

### creation d'une entreprise
POST http://localhost:3000/api/company
Content-Type: application/json

{
    "name": "Entreprise créée",
    "siret": "51234567891234",
    "localisation": "Pau"
}
### Récupérer l'entreprises de l'utilisateur
GET http://localhost:3000/api/company/companyProfile
Content-Type: application/json

### creation d'une entreprise
GET http://localhost:3000/api/company
Content-Type: application/json
# {
#     "name": "Entreprise créée",
#     "siret": "51234567891234",
#     "localisation": "Pau"
# }

// Test sanitize
{
    "name": "totoDev<script>alert('XSS')</script>",
    "siret": "51234567891234",
    "localisation": "Pau"
}

### Modification d'une entreprise
PATCH http://localhost:3000/api/company/4
Content-Type: application/json

{
    "name": "Entreprise modifiée"
}

### Suppression d'une entreprise
DELETE http://localhost:3000/api/company/1
Content-Type: application/json

### creation d'un user
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "email": "lena3.webhook@exemple.com",
    "password": "gargouille3001"
}

// TEST SECURITY SANITYSE-HTML
# {
#         "email": "lena5.webhook@exemple.com<script>alert('XSS')</script>",
#         "password": "gargouille3001"
# }



### Modifier les informations
PATCH http://localhost:3000/api/user
Content-Type: application/json

{
    "lastname": "Cynthia",
    "firstname": "Postgres",
    "phonenumber": "01010101010",
    "email": "emma.postgres@exemple.com",
    "password": "gargouille2025"
}

### authentification admin
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "robin.syntaxe@exemple.com",
    "password": "gargouille2026"
}

### authentification user
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "lena.webhook@exemple.com",
    "password": "gargouille3001"
}


### Voir ses informations personnelles
GET http://localhost:3000/api/user/profile
Content-Type: application/json

### trier les user
GET http://localhost:3000/api/admin/user/filter?by=lastnameSelected
Content-Type: application/json

### lister les user
GET http://localhost:3000/api/admin/user
Content-Type: application/json

### Récuperer 1 user
GET http://localhost:3000/api/admin/user/2
Content-Type: application/json

### Désactiver un user (admin)
PATCH http://localhost:3000/api/admin/user/2
Content-Type: application/json

{
    "isActive": false
}

### Récupérer les messages
GET http://localhost:3000/api/message-contact
Content-Type: application/json

### créer un message
POST   http://localhost:3000/api/message-contact/
Content-Type: application/json

{
    "mail": "test@mail.com",
    "message": "Je suis un test de message"
}

### modifier les messages
PATCH  http://localhost:3000/api/message-contact/8
Content-Type: application/json

{
    "status": "non lu"
}

### Supprimer les messages
Delete  http://localhost:3000/api/message-contact/5
Content-Type: application/json

### Récupérer les genres
GET http://localhost:3000/api/genre
Content-Type: application/json


### creation d'une genre
POST http://localhost:3000/api/admin/genre
Content-Type: application/json

{
    "label": "Pop Rock"
}

### Modification d'un genre
PATCH http://localhost:3000/api/admin/genre/3
Content-Type: application/json

{
    "label": "Classique"
}

### Suppression d'un genre 
DELETE http://localhost:3000/api/admin/genre/3
Content-Type: application/json


### listes des projets
GET http://localhost:3000/api/admin/project/
Content-Type: application/json

### trier les projets par statuts
GET http://localhost:3000/api/admin/project/filter?status=en cours
Content-Type: application/json

### modifier le statut
PATCH http://localhost:3000/api/admin/project/1
Content-Type: application/json

### supprimer le projet
DELETE http://localhost:3000/api/admin/project/2
Content-Type: application/json


### faire une demande de projet
POST http://localhost:3000/api/project
Content-Type: application/json

{
    "name": "toto"
}

### voir la liste de ses projets
GET http://localhost:3000/api/project
Content-Type: application/json


### trier par statut
GET http://localhost:3000/api/project/filter?status=en cours
Content-Type: application/json


### Obtenir les descriptions
GET http://localhost:3000/api/description
Content-Type: application/json

### creation d'une description
POST http://localhost:3000/api/admin/description
Content-Type: application/json

{
    "title": "Nouveau titre",
    "image_link": "lien à venir",
    "text": "Nouvelle description"
}


### Modification d'une description
PATCH http://localhost:3000/api/admin/description/1
Content-Type: application/json

{
    "text": "Modification description"
}


### Suppression d'une description
DELETE http://localhost:3000/api/admin/description/2
Content-Type: application/json

### Récupérer tous les extraits star
GET http://localhost:3000/api/preview/star
Content-Type: application/json

### Récupérer tous les extraits filtrés par genre jazz
GET http://localhost:3000/api/preview/filter?genre=jazz
Content-Type: application/json

### Récupérer tous les extraits triés par dates
GET http://localhost:3000/api/preview/filter
Content-Type: application/json


### Modification d'un extrait
PATCH http://localhost:3000/api/admin/preview/1
Content-Type: application/json

{
    "title": "Extrait modifié"
}

### Suppression d'un extrait
DELETE http://localhost:3000/api/admin/preview/4
Content-Type: application/json